### ISSUE TITLE
win_getid and empty dictionary keys in vim 7.4.1099

### ISSUE THREAD

**Issue by mgumbley-resilient** [rbong/vim-crystalline#12]
Hi, I'm enjoying vim-crystalline on macOS / vim 8 (it's great! many thanks!), but wanted to also use it on CentOS 7.6, which has vim 7.4.1099 as standard. When I install the latest version from master (4634c5f), I see the following errors:

Error detected while processing /root/.vim/plugin/crystalline.vim:
line   11:
E713: Cannot use empty key for Dictionary
E15: Invalid expression: { 'n': ' NORMAL ', 'i': ' INSERT ', 'v': ' VISUAL ', 'R': ' REPLACE ', '': '', }
line   19:
E713: Cannot use empty key for Dictionary
E15: Invalid expression: { 'n': 'NormalMode', 'i': 'InsertMode', 'v': 'VisualMode', 'R': 'ReplaceMode', '': '', }

Error detected while processing /root/.vim/plugin/crystalline.vim:
line   32:
E713: Cannot use empty key for Dictionary
E15: Invalid expression: { 'NormalMode': ['', 'Fill', 'TabFill', 'Tab'], 'InsertMode': ['', 'Fill', 'TabFill', 'Tab'], 'VisualMode': ['', 'Fill', 'TabFill', 'Tab'], 'ReplaceMode': ['', 'Fill', 'TabFill', 'Tab'], '': ['Fill'], 'Inactive': [], 'Fill': [], 'Tab': ['TabSel', 'TabFill', 'NormalMode', 'InsertMode', 'VisualMode', 'ReplaceMode'], 'TabType': ['Tab', 'TabSel', 'TabFill', 'NormalMode', 'InsertMode', 'VisualMode', 'ReplaceMode'], 'TabSel': ['Tab', 'TabFill'], 'TabFill': [], }
Error detected while processing function crystalline#set_statusline:
line    2:
E117: Unknown function: win_getid
E15: Invalid expression: 'set statusline=%!crystalline#get_statusline(1,' . win_getid() . ')'
Error detected while processing function crystalline#set_theme..crystalline#theme#default#set_theme:
line    1:
E713: Cannot use empty key for Dictionary
E116: Invalid arguments for function crystalline#generate_theme

I'm using the Tomorrow theme, fugitive plugin, and the following initialisation:
function! StatusLine(current, width)
  let l:s = ''

  if a:current
    let l:s .= crystalline#mode() . crystalline#right_mode_sep('')
  else
    let l:s .= '%#CrystallineInactive#'
  endif
  let l:s .= ' %f%h%w%m%r '
  if a:current
    let l:s .= crystalline#right_sep('', 'Fill') . ' %{fugitive#head()}'
  endif

  let l:s .= '%='
  if a:current
    let l:s .= crystalline#left_sep('', 'Fill') . ' %{&paste ?"PASTE ":""}%{&spell?"SPELL ":""}'
    let l:s .= crystalline#left_mode_sep('')
  endif
  if a:width > 80
    let l:s .= ' %{&ft}[%{&enc}][%{&ffs}] %l/%L %c%V %P '
  else
    let l:s .= ' '
  endif

  return l:s
endfunction

function! TabLine()
  let l:vimlabel = has('nvim') ?  ' NVIM ' : ' VIM '
  return crystalline#bufferline(2, len(l:vimlabel), 1) . '%=%#CrystallineTab# ' . l:vimlabel
endfunction

let g:crystalline_enable_sep = 1
let g:crystalline_statusline_fn = 'StatusLine'
let g:crystalline_tabline_fn = 'TabLine'
let g:crystalline_theme = 'default'

I'd try to fix the above problems and submit a PR, but don't have vim-scripting-fu.
Kind regards,
Matt

**Comment by rbong** [comment]
Ah... that is quite unfortunate. Using empty strings for a dictionary key is essential to keeping the separator interface succinct. For now all of the keys correspond to a highlight group. For example, the key `Fill` corresponds to `CrystallineFill`. The empty string group corresponds to `Crystalline`. One potential is to rename it to `CrystallineLine` and name the key `Line`. As awkward as that name is, it's consistent with Vim highlight groups.

Also, I would expect that most people are already using the current interface in their statuslines.

So this probably won't get fixed in the main version for a while. However, I will start a branch for this fix.

**Comment by rbong** [comment]
Please use branch [vim-7](https://github.com/rbong/vim-crystalline/tree/vim-7) for the fix

Unfortunately I am having problems with Docker and was not able to test with vim 7, please let me know how it works.

**Comment by rbong** [comment]
Having trouble with testing on travis as well. Patches welcome, since I do not use vim 7.

**Comment by mgumbley-resilient** [comment]
Thank you! I'll try it now!
After clearing out master version, and unzipping the vim-7 branch into my .vim, I still see:

Error detected while processing /root/.vim/plugin/crystalline.vim:
line   11:
E713: Cannot use empty key for Dictionary
E15: Invalid expression: { 'n': ' NORMAL ', 'i': ' INSERT ', 'v': ' VISUAL ', 'R': ' REPLACE ', '': '', }
line   19:
E713: Cannot use empty key for Dictionary
E15: Invalid expression: { 'n': 'NormalMode', 'i': 'InsertMode', 'v': 'VisualMode', 'R': 'ReplaceMode', '': '', }
Error detected while processing function crystalline#set_statusline:
line    2:
E117: Unknown function: win_getid
E15: Invalid expression: 'set statusline=%!crystalline#get_statusline(1,' . win_getid() . ')'

(when starting vim, then, after pressing return a few times...)

Error detected while processing function crystalline#get_tabline..TabLine..crystalline#bufferline..crystalline#tab_sep:
line   17:
E121: Undefined variable: g:crystalline_mode_hi_groups

and

Error detected while processing function crystalline#get_tabline..TabLine..crystalline#bufferline..crystalline#tab_sep:
line   17:
E15: Invalid expression: g:crystalline_mode_hi_groups[crystalline#mode_type()]

Many thanks, Matt

**Comment by mgumbley-resilient** [comment]
Just nosing around in the nerdtree plugin (grepping for win_getid) and the author does:

        " Use the window ID to identify the currently active window or fall
        " back on the buffer ID if win_getid/win_gotoid are not available, in
        " which case we'll focus an arbitrary window showing the buffer.
        let l:useWinId = exists('*win_getid') && exists('*win_gotoid')

        if winnr() == s:NERDTree.GetWinNum()
            call nerdtree#exec("wincmd p", 1)
            let l:activeBufOrWin = l:useWinId ? win_getid() : bufnr("")
            call nerdtree#exec("wincmd p", 1)
        else
            let l:activeBufOrWin = l:useWinId ? win_getid() : bufnr("")
        endif

Not sure if that helps?!

Kind regards,
Matt

**Comment by rbong** [comment]
I've pushed up some extra fixes.

I'm now using `' '` (space) instead of `''` (empty string) for the unknown mode. This should remove the additional empty dictionary keys.

I've added a feature check for `win_getid`. Unfortunately, without `win_getid`, the width check won't work properly for now.

**Comment by mgumbley-resilient** [comment]
Hi, I've tried the above, but am still seeing this on startup:

E15: Invalid expression: a:group_a == v:null || a:group_b == v:null
Press ENTER or type command to continue
Error detected while processing function crystalline#get_statusline..StatusLine..crystalline#right_mode_sep..crystalline#mode_sep..crystalline#sep:
line    5:
E121: Undefined variable: v:null
Press ENTER or type command to continue
Error detected while processing function crystalline#get_statusline..StatusLine..crystalline#right_mode_sep..crystalline#mode_sep..crystalline#sep:
line    5:
crystalline#get_statusline(1,0)
Press ENTER or type command to continue
Error detected while processing function crystalline#get_statusline..StatusLine..crystalline#right_mode_sep..crystalline#mode_sep..crystalline#sep:
line    5:
E121: Undefined variable: v:null

Kind regards,
Matt

**Comment by rbong** [comment]
I will get an instance of Vim 7 running and try again.

**Comment by rbong** [comment]
Sorry for the long wait. The `v:null` issue should be resolved and launching in vim 7 should now be possible.

Edit: some older versions like 1099 still won't work. Working this out now.

Edit: alright, NOW 7.4.1099 works.

**Comment by rbong** [comment]
I've got a good way to test support now and the branch is up to date with master. I've started thinking about consolidating the master branch and the vim-7 branch, and I don't think it's possible for now without some sacrifices. I am going to keep using the branch model.

If you have vim 7, use this to install crystalline:

```vim
Plug 'rbong/vim-crystalline', { 'branch': 'vim-7' }
```

**Comment by mgumbley-resilient** [comment]
Hi, thank you for continuing to work on this - just tested on 1099, and it works perfectly!
Kind regards,
Matt
